### ISSUE TITLE
Login and Signup Components need a KeyboardAvoidingView

### ISSUE THREAD

**Issue by jambis** [Lambda-School-Labs/mydish-fe#39]
Login and Signup component could use a KeyboardAvoidingView the other good stuff so the keyboard doesn't block the input fields.

https://github.com/Lambda-School-Labs/cooking-recipe-source-control-fe/blob/e4238de07c150edeb67336e8b71dcd37af207851/components/Login.js#L37

**Comment by DevWarr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Login/SignUp components need a KeyBoardAvoidingView component](https://trello.com/c/IOwwoeg0/50-login-signup-components-need-a-keyboardavoidingview-component)

**Comment by jambis** [comment]
I have gone and added a KeyboardAvoidingView and removed unnecessary x button in the top right corner  [Pull Request](https://github.com/Lambda-School-Labs/cooking-recipe-source-control-fe/pull/48)
